# Generated by Django 5.1.3 on 2024-12-31 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization issuing the receipt', max_length=255, unique=True)),
                ('address', models.TextField(help_text='Address of the organization')),
                ('contact_email', models.EmailField(help_text='Contact email of the organization', max_length=255, unique=True)),
                ('contact_number', models.CharField(help_text='Contact number of the organization', max_length=15, unique=True)),
                ('website', models.URLField(blank=True, help_text='Website of the organization', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the organization', null=True, upload_to='organization_logos/')),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organization was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the organization profile was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the recipient', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the recipient', max_length=255, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the recipient', max_length=15, null=True, unique=True)),
                ('address', models.TextField(blank=True, help_text='Address of the recipient', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the recipient was added')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(help_text='Name of the recipient', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the transaction')),
                ('billing_address', models.TextField(help_text='Billing address')),
                ('description', models.TextField(blank=True, help_text='Description of the transaction', null=True)),
                ('receipt_number', models.CharField(default=uuid.uuid4, help_text='Unique receipt number', max_length=50, unique=True)),
                ('organization', models.ForeignKey(help_text='Organization issuing the receipt', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.organization')),
            ],
        ),
    ]
